services:
  node-js-app:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/books
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: books
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d books"]
      interval: 5s
      timeout: 5s
      retries: 5
